### ISSUE TITLE
Optimal parallelization

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/us_ensembles#2]
It's very easy for me to parallelize by state. 

I can also run multiple chains per state -- what's our running time per chain, and, given that, (and the difficulty associated with merging chains), should I run a few chains per state, or just one?

**Comment by nickeubank** [comment]
Oh, also: once you've picked a number of steps, can you give a guess of running time? I have to specify a "wall time" (the time we want the scheduler to allocate us the hardware -- setting too long means will take a little longer for the scheduler to find us free resources, but setting short means our job will be canceled, so better to error on the side of picking too much time.

**Comment by drdeford** [comment]
I'll do a little longer testing locally to try to get an estimate. Luckily, since we are writing the data to file every so often, the scaling is pretty linear in number of chain steps. 

For the number of chains per state, I like 3 if we have that many cores available. We can set it up to use a different starting seed for each which will let us run some convergence checks (I don't expect any problems).

**Comment by nickeubank** [comment]
Great, will code up expecting 3 per state.

**Comment by drdeford** [comment]
Cool! It may be easiest just to add the three plans to each dual graph json so they are all in one place.

**Comment by nickeubank** [comment]
lost me there... was thinking in 15_build_graph.py I'd just write a `for run in range(3)` loop over building of graphs?

**Comment by drdeford** [comment]
That would work too - I was just thinking you could wrap lines 116-121 in a for loop and just add New_Seed0, New_Seed1, New_Seed2 as attributes - this way you don't have to build the whole graph three times.

**Comment by nickeubank** [comment]
ah, ok. I think I did something analogous -- see 7e25b76  -- that gonna work ok?

**Comment by drdeford** [comment]
Yeah, that looks fine to me.

**Comment by nickeubank** [comment]
great.

**Comment by drdeford** [comment]
I'm trying out some 10k runs for time testing now, with a couple of tweaks to the I/O to make fewer total calls.

**Comment by nickeubank** [comment]
Great! Got everything running on slurm. Just gonna finish fixing the three problem states:

![image](https://user-images.githubusercontent.com/9683693/71684476-98fdbf00-2d63-11ea-84b4-d692cda4d13c.png)

**Comment by drdeford** [comment]
Sweet! I think the one last code snippet I need to insert is just an anti-sticking check - once in a while you can get unlucky with a merge, in the sense that it might take exponentially many tries to draw a cuttable tree. This is pretty unlikely for congressional districts with the bounds we are using but across all 50 states at once, I certainly expect some amount of weirdness. Luckily, it is easy to shortcircuit if this happens.

**Comment by nickeubank** [comment]
Yay! :) Can it "fail" in a manner that doesn't crash the process?

Just need to get these few states to work. I may just fix them in ArcGIS and save them. Not quite replicable, but geopandas is just so bad with spatial joins and overlays (I tried to "clip" florida census boundaries using `overlay` instead of `sjoin`, and it was running for over an hour when I gave up...)

**Comment by drdeford** [comment]
Yeah, the fix is to set a number of tree drawing attempts (10-20ish seems to be enough to avoid most false positives) and then simply return an empty flip dictionary to the chain for the step, which will make it select a new pair of districts to merge - no crashing required. 

It is really only a concern for the larger states, where the population balance `wiggle room' can add up over all the districts to create adjacent pairs that are either both very close to the population boundary. In this case, there may be relatively few trees that would restore the original partition (and here relatively few can mean something like 1 in 10^(300) )
